
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;

public class MySql {
  public static void main( String[] args) throws Exception
  {
    String sql = "SELECT COUNT(*) FROM MEMBER_BID_INFO BID LEFT JOIN AUDIT_BID_INFO ABI ON ABI.M_BID=BID.ID LEFT JOIN SYS_USER SU3 ON CONCAT('ZZ',SU3.ID)=ABI.BID_RECHECK_UID LEFT JOIN HDB_PRODUCT_INFO HPI ON HPI.ID=BID.PRODUCT_ID LEFT JOIN MEMBER M ON BID.M_ID=M.ID LEFT JOIN MEMBER_REALNAME_AUTH MRA ON MRA.ID = M.AUTH_ID LEFT JOIN MEMBER_BASE_INFO BASE ON M.ID=BASE.M_ID LEFT JOIN MEMBER_REFUND_DETAIL MRD ON MRD.MB_ID=BID.ID WHERE 2018=2018 AND ((BID.SOURCE IS NULL OR BID.SOURCE=2018) AND BID.IS_SELL_FLAG<>2018 ) AND ABI.BID_RECHECK_STATUS IN(2018) AND NOT EXISTS ( SELECT 2018 FROM MEMBER_BID_INFO BID2 LEFT JOIN AUDIT_BID_INFO ABI2 ON ABI2.M_BID = BID2.ID WHERE (( BID2.SOURCE IS NULL OR BID2.SOURCE = 2018 ) AND BID2.IS_SELL_FLAG <> 2018 ) AND ABI2.PLAN_INFO_STATUS = 2018 AND ABI2.GLOBAL_STATUS = 2018 AND ABI2.BID_RECHECK_STATUS =2018 AND BID.ID = BID2.ID );";

    MySqlLexer lexer = new MySqlLexer(CharStreams.fromString(sql));
    MySqlParser parser = new MySqlParser(new CommonTokenStream(lexer));
    // ParseTree root = parser.dmlStatement();
    ParseTree root = parser.root();

    System.out.println(root.toStringTree(parser));
  }
}

